server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/oauth2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

redirectUri: "http://localhost:8080"
TOKEN:
  SECRET_KEY: t-tajiri
  EXPIRATION_TIME: 1_800_000 # 30 min
